---
title: "R resources"
output:
  html_notebook: default
---

##Links to R resources

This is an excelent __introductory course__ in R: [ModernDive: Statistical Inference via Data Science](https://moderndive.com/ "Introductory course book")  

This is good material for an __R workshop of a day__ or more: [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/ "1+ day R workshop")

Another workshop on __programming with R__ from the same source: [Programming with R](https://swcarpentry.github.io/r-novice-inflammation/)

This is a good free __online book__ to get you started with emphasis on usage of __modern packages for exploring data__ (not for hypothesis testing): 
[R for Data Science](https://r4ds.had.co.nz/)

A good reference to find __known solutions for common problems__: [Cookbook for R](http://www.cookbook-r.com/)

These are recomendations for a __scientific project setup__: [Good enough practices in scientific computing](https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/blob/gh-pages/good-enough-practices-for-scientific-computing.pdf)

Here we have a __free online R book on econometrics!__ [Principles of econometrics with R](https://bookdown.org/ccolonescu/RPoE4/)

And another __free online R book on econometrics!__[Introduction to Econometrics with R](https://www.econometrics-with-r.org/)

An indepth course on analyzing data in excel and R from the Texas University, including material on __robust regression__: [From Data to Decisions: Measurement, Uncertainty, Analysis, and Modeling](http://www.lithoguru.com/scientist/statistics/course.html)

This free online book/course has a short introduction, more material on ggplot2 and even more on statistics: [R statistics](http://r-statistics.co/ "R articles on statistics, including regression") 

This is an exhaustive playlist on youtube: [__R for economists__](https://www.youtube.com/playlist?list=PLcTBLulJV_AIuXCxr__V8XAzWZosMQIfW)

More free online books/courses to learn about R:
[Free online R books](http://cmdlinetips.com/2018/01/free-online-resources-books-to-learn-r-and-data-science/)  

For importing datasets, [read this manual](https://support.rstudio.com/hc/en-us/articles/218611977-Importing-Data-with-RStudio).

For practical use of R notebooks you need to know the markdown markup language:
[Markdown demo](https://markdown-it.github.io "Help on markdown")  

To use R in an version controlled environment
[Happy Git with R](https://happygitwithr.com/ "R workflow with Git")  

An example of [Robust regression](https://rpubs.com/dvallslanaquera/robust_regression)  

More information on R programming: [Advanced R](http://adv-r.had.co.nz/ "free online book on R programming")  

Be warned for [The null ritual pdf](http://library.mpib-berlin.mpg.de/ft/gg/GG_Null_2004.pdf "On the ritual of null hypothesis testing")

To analyse the result of a model, use the [The broom package](https://github.com/tidymodels/broom "To access model results as dataframes")

[Datasets in packages](https://vincentarelbundock.github.io/Rdatasets/datasets.html)

[Linear regression assumptions and diagnostics in R](http://www.sthda.com/english/articles/39-regression-model-diagnostics/161-linear-regression-assumptions-and-diagnostics-in-r-essentials/)
